export type Cadence = "daily" | "weekly" | "monthly";

export type Weekday = 1 | 2 | 3 | 4 | 5 | 6 | 7; // ISO: 1=Mon ... 7=Sun

export type ClerkUser = {
  userId: string; // internal id (often Entra object id)
  displayName: string;
};

export type SharedWeekRule = {
  enabled: boolean;
  weekNumbers: number[]; // ISO week numbers that are shared weeks (e.g., [10,14,...]) OR generated by rule in future
  users: { userId: string; displayName: string }[];
  weekdayAssignment: Record<Weekday, string>; // maps weekday -> userId
};

export type RotationConfig = {
  timezone: string; // e.g. "Europe/Copenhagen"
  roster: ClerkUser[]; // ordered list for single-clerk weeks
  sharedWeekRule: SharedWeekRule;
};

export type TaskDefinition = {
  id: string;
  title: string;
  cadence: Cadence;
  active: boolean;
  weekdaysOnly?: boolean; // for daily tasks
  preferredWeekday?: Weekday; // e.g. milk/beans prefer Monday=1
};

export type HolidayConfig = {
  countryCode: "DK";
  skipDailyOnHolidays: boolean;
};

export type BotConfig = {
  rotation: RotationConfig;
  holiday: HolidayConfig;
  tasks: TaskDefinition[];
  reminder: {
    hour: number; // 0-23 local time
    minute: number; // 0-59
    weekdaysOnly: boolean;
  };
  announcement: {
    teamsChannelConversationId?: string;
  };
  admins: {
    allowedEntraObjectIds: string[];
  };
};

export type TaskInstanceStatus = "open" | "done";

export type TaskInstance = {
  id: string;
  taskDefinitionId: string;
  periodKey: string; // e.g. 2026-W12 or 2026-03
  dueDate?: string; // YYYY-MM-DD if daily
  assignedToUserId: string;
  status: TaskInstanceStatus;
  doneAt?: string; // ISO
  doneByUserId?: string;
};

